spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentdb
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update        # auto-creates/updates tables on startup
    show-sql: true            # logs SQL queries (useful for learning)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

app:
  jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
    expiration-ms: 86400000   # 24 hours

server:
  port: 8080
